version: '3.8'

services:
    localstack:
        image: localstack/localstack
        container_name: localstack
        ports:
            - "4566:4566"
            - "4510-4559:4510-4559"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
