# pihole-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
# pihole-secret.yaml - Use a Secret instead of ConfigMap for passwords
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
type: Opaque
stringData:
  WEBPASSWORD: "my-secret-password" # Replace with your password
---
# pihole-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  DNS1: "1.1.1.1"
  DNS2: "9.9.9.9"
  TZ: "Europe/Madrid"
  VIRTUAL_HOST: "pi.hole"
  ServerIP: "0.0.0.0"
  DNSMASQ_LISTENING: "all"
  FTLCONF_LOCAL_IPV4: "0.0.0.0"
  FTLCONF_MAXDBDAYS: "7" # Reduce database retention to save space
---
# pihole-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
# pihole-dnsmasq-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
# pihole-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2025.03.0 # Specify exact version for stability
          resources:
            limits:
              cpu: 500m # Reduced from 1000m
              memory: 300Mi # Reduced from 512Mi
            requests:
              cpu: 100m # Reduced from 200m
              memory: 200Mi # Reduced from 256Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN # Required for DNS
                - NET_BIND_SERVICE # Required to bind to ports < 1024
                - SYS_NICE # For process priority
                - SYS_TIME # For NTP functionality
                - CAP_SYS_NICE
          env:
            - name: DNS1
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: DNS1
            - name: DNS2
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: DNS2
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: TZ
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
            - name: VIRTUAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: VIRTUAL_HOST
            - name: ServerIP
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: ServerIP
            - name: DNSMASQ_LISTENING
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: DNSMASQ_LISTENING
            - name: FTLCONF_LOCAL_IPV4
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: FTLCONF_LOCAL_IPV4
            - name: FTLCONF_MAXDBDAYS
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: FTLCONF_MAXDBDAYS
          ports:
            - containerPort: 80
              name: http
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
          readinessProbe:
            tcpSocket: # Use TCP socket check instead of HTTP
              port: 53
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe: # Add startup probe to give container time to start
            tcpSocket:
              port: 53
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 12 # 120 seconds (12 * 10s) to start up
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
---
# pihole-service-tcp.yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
  selector:
    app: pihole
---
# pihole-service-udp.yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
  selector:
    app: pihole
