services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    ports:
      - "8384:8384"  # Web UI
      - "22000:22000/tcp"  # TCP file transfer
      - "22000:22000/udp"  # QUIC file transfer
      - "21027:21027/udp"  # Discovery broadcasts
    volumes:
      - /mnt/nfs/syncthing:/var/syncthing  # Shared directory
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
