# storage-class.yaml - Defines a storage class optimized for database workloads

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-default
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
